[[jenkins-setup]]
= Jenkins環境構築
include::base_attributes.adoc[]
// jenkinsのホストのIPアドレス
:jenkins-web-server-host-addr: localhost
// jenkinsのポート番号
:jenkins-port: 8080

本章では、Docker上にJenkins環境を構築する手順を説明する。

== 環境

xref:docker_setup.adoc#docker-setup[Docker環境構築] に従い環境構築実施済み。

== インストール

https://www.jenkins.io/doc/book/installing/docker/#on-macos-and-linux に従う。

以下の説明は一部で上記ドキュメントを機械翻訳している。

[[create-bridge-network]]
=== ブリッジネットワークを作成

Dockerコンテナ間で通信するにはブリッジネットワークを作成する必要があるので作成する。

[source, console, linenums]
----
$ docker network create jenkins
7ed5933dba63bd8a096d1ecab7d4bdcfb0bd862f4e0fb93bb3c4d39a4a768644
----

=== "docker:dind"イメージを実行

Docker内部のコンテナでJenkinsを実行しているとき、デフォルトではDockerコマンドを使用することができない。
Jenkinsコンテナ内でDockerコマンドを使用するには、以下の手順で `docker:dind` イメージを実行する。

[NOTE]
====
DockerコンテナからDockerを使うには、Docker in Docker(DinD)とDocker outside of Docker (DooD)の2種類の方法がある。
一般にCI用途ではDooDを使うのが好ましいとされているが、Jenkins公式ドキュメントにはDinDを使用する手順が記載されているので、これに従う。
====

[source, bash, linenums]
----
docker run \
  --name jenkins-docker \# <1>
  --rm \# <2>
  --detach \# <3>
  --privileged \# <4>
  --network jenkins \# <5>
  --network-alias docker \# <6>
  --env DOCKER_TLS_CERTDIR=/certs \#<7>
  --volume jenkins-docker-certs:/certs/client \# <8>
  --volume jenkins-data:/var/jenkins_home \# <9>
  --publish 2376:2376 \# <10>
  docker:dind \# <11>
  --storage-driver overlay2 # <12>
----
<1> (オプション)イメージの実行に使用するDockerコンテナ名を指定します。デフォルトでは、Dockerはコンテナの一意の名前を生成します。
<2> (オプション)シャットダウン時にDockerコンテナ(Dockerイメージのインスタンス)を自動的に削除します。
<3> (オプション)バックグラウンドでDockerコンテナを実行します。このインスタンスは、後で `docker stop jenkins-docker` を実行して停止できます。
<4> DockerでDockerを実行するには、現在、正しく機能するために特権アクセスが必要です。この要件は、新しいLinuxカーネルバージョンで緩和される可能性があります。
<5> これは、前の手順で作成したネットワークに対応しています。
<6> Dockerコンテナ内のDockerを `jenkins` ネットワーク内のホスト名 `docker` として使用できるようにします。
<7> DockerサーバーでのTLSの使用を有効にします。特権コンテナを使用するため、これをお勧めしますが、以下で説明する共有ボリュームを使用する必要があります。この環境変数は、Docker TLS証明書が管理されるルートディレクトリを制御します。
<8> コンテナ内の `/certs/client` ディレクトリを、上記で作成した `jenkins-docker-certs` という名前のDockerボリュームにマップします。
<9> コンテナ内の `/var/jenkins_home` ディレクトリを `jenkins-data` という名前のDockerボリュームにマップします。これにより、このDockerコンテナのDockerデーモンによって制御される他のDockerコンテナがJenkinsからデータをマウントできるようになります。
<10> （オプション）ホストマシンのDockerデーモンポートを公開します。これは、ホストマシンで `docker` コマンドを実行して、この内部Dockerデーモンを制御する場合に役立ちます。
<11> `docker:dind` イメージ自体。このイメージは、コマンド `docker image pull docker:dind` を使用して、実行する前にダウンロードできます。
<12> Dockerボリュームのストレージドライバー。サポートされているオプションについては、「Dockerストレージドライバー」を参照してください。

[[customise-official-jenkins-docker-image]]
=== 公式のJenkins Dockerイメージをカスタム

. 以下の内容でDockerfileを作成する
+
[source, dockerfile, options="linenums,nowrap"]
.Dockerfile
----
FROM jenkins/jenkins:2.346.2-jdk11
USER root
RUN apt-get update && apt-get install -y lsb-release
RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
  https://download.docker.com/linux/debian/gpg
RUN echo "deb [arch=$(dpkg --print-architecture) \
  signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
  https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
RUN apt-get update && apt-get install -y docker-ce-cli
USER jenkins
RUN jenkins-plugin-cli --plugins "blueocean:1.25.6 docker-workflow:1.29"
----
. 作成したDockerfileからDockerイメージをビルドする
+
[source, bash, linenums]
----
docker build -t myjenkins-blueocean:2.346.2-1 .
----

=== 作成したDockerイメージを実行

以下のコマンドにより、<<customise-official-jenkins-docker-image>>でビルドしたDockerイメージを実行する。

[source, bash, linenums]
----
docker run \
  --name jenkins-blueocean \# <1>
  --restart=on-failure \# <2>
  --detach \# <3>
  --network jenkins \# <4>
  --env DOCKER_HOST=tcp://docker:2376 \# <5>
  --env DOCKER_CERT_PATH=/certs/client \
  --env DOCKER_TLS_VERIFY=1 \
  --publish 8080:8080 \# <6>
  --publish 50000:50000 \# <7>
  --volume jenkins-data:/var/jenkins_home \# <8>
  --volume jenkins-docker-certs:/certs/client:ro \# <9>
  myjenkins-blueocean:2.346.2-1 # <10>
----
<1> （オプション）DockerイメージのこのインスタンスのDockerコンテナ名を指定します。
<2> コンテナが停止した場合は、常に再起動します。手動で停止した場合は、Dockerデーモンが再起動したとき、またはコンテナ自体が手動で再起動したときにのみ再起動します。
<3> （オプション）現在のコンテナをバックグラウンドで実行し（つまり「デタッチ」モード）、コンテナIDを出力します。このオプションを指定しない場合、このコンテナの実行中のDockerログがターミナルウィンドウに出力されます。
<4> このコンテナを、<<create-bridge-network>>で定義した``jenkins``ネットワークに接続します。これにより、Dockerデーモンが、ホスト名``docker``を介してこのJenkinsコンテナで使用できるようになります。
<5> 前の手順でDockerデーモンに接続するために``docker``, ``docker-compose``, およびその他のDockerツールで使用される環境変数を指定します。
<6> 現在のコンテナのポート8080をホストマシンのポート8080にマップ（つまり「公開」）します。最初の数字はホストのポートを表し、最後の数字はコンテナのポートを表します。したがって、このオプションに``-p 49000:8080``を指定した場合、ポート49000を介してホストマシン上のJenkinsにアクセスすることになります。
<7> （オプション）現在のコンテナのポート50000をホストマシンのポート50000にマップします。これは、他のマシンに1つ以上のインバウンドJenkinsエージェントをセットアップし、それが``jenkins-blueocean``コンテナ（Jenkins「コントローラー」）と対話する場合にのみ必要です。インバウンドJenkinsエージェントは、デフォルトでTCPポート50000を介してJenkinsコントローラーと通信します。 Jenkinsコントローラーのこのポート番号は、[グローバルセキュリティの構成]ページから変更できます。 Jenkinsコントローラーの**インバウンドJenkinsエージェントのTCPポート**を（たとえば）51000に変更する場合は、（この``docker run…``コマンドを使用して）Jenkinsを再実行し、この「publish」オプションを何かで指定する必要があります。``--publish 52000:51000``のように、最後の値はJenkinsコントローラーでこの変更された値と一致し、最初の値はJenkinsコントローラーをホストしているマシンのポート番号です。インバウンドJenkinsエージェントは、そのポート（この例では52000）でJenkinsコントローラーと通信します。 WebSocketエージェントはこの構成を必要としないことに注意してください。
<8> コンテナ内の``/var/jenkins_home``ディレクトリを``jenkins-data``という名前のDockerボリュームにマップします。
footnote:[ボリュームはホスト側の``~/.local/share/docker/volumes/ボリューム名/``に作成される。]
footnote:[コンテナにマウントされているボリュームは``docker inspect コンテナID``で出力される内容の"Mounts"に記載されている。]
``/var/jenkins_home``ディレクトリをDockerボリュームにマッピングする代わりに、このディレクトリをマシンのローカルファイルシステム上のディレクトリにマッピングすることもできます。たとえば、オプション
``--volume $HOME/jenkins:/var/jenkins_home``は、コンテナの``/var/jenkins_home``ディレクトリをローカルマシンの``$HOME``ディレクトリ内の``jenkins``サブディレクトリにマップします。通常は``/Users/<your-username>/jenkins``または``/home/<your-username>/jenkins``。このためにソースボリュームまたはディレクトリを変更する場合は、上記の``docker:dind``コンテナのボリュームをこれに一致するように更新する必要があることに注意してください。
<9> ``/certs/client``ディレクトリを以前に作成した``jenkins-docker-certs``ボリュームにマップします。これにより、Dockerデーモンに接続するために必要なクライアントTLS証明書が、``DOCKER_CERT_PATH``環境変数で指定されたパスで使用できるようになります。
<10> 前の手順で作成したDockerイメージの名前。

== 初期設定

https://www.jenkins.io/doc/book/installing/docker/#setup-wizard に従う。

=== Unlock Jenkins

http://{jenkins-web-server-host-addr}:{jenkins-port}/ にアクセスする。
adminユーザの初期パスワードを入力する。

初期パスワードはコンテナ内の``/var/jenkins_home/secrets/initialAdminPassword``に記載されている。

ファイルの内容を表示するには、``docker exec コンテナ名 cat /var/jenkins_home/secrets/initialAdminPassword``を実行する。
あるいは以下の手順で実行中のコンテナに接続して表示してもよい。

// "nowrap"で長い行の折り返しを無効にする
[source, bash, options="linenums,nowrap"]
----
# 実行中のコンテナ一覧を出力
$ docker ps
CONTAINER ID   IMAGE                       COMMAND                  CREATED          STATUS          PORTS                                                  NAMES
137f055ee35e   jenkins/jenkins:lts-jdk11   "/usr/bin/tini -- /u…"   17 minutes ago   Up 17 minutes   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 50000/tcp   determined_archimedes

# 上で確認したコンテナ名を指定してシェルを起動
$ docker exec -it determined_archimedes bash

# ファイルを参照
$ cat /var/jenkins_home/secrets/initialAdminPassword
b528f9670cf44323917d05f83af7108d

# コンテナから切断
$ exit
----

=== Customize Jenkins

"Install suggested plugins"を選択する。
推奨されるプラグインがインストールされる。

=== Create First Admin User

管理者ユーザを作成する。
ユーザー名、パスワード、フルネーム、メールアドレスをよしなに設定する。

ここでは以下のとおり設定したものとする。

* ユーザー名: admin
* パスワード: jenkins

=== Instance Configuration

JenkinsのURLを指定する。
ここでは外部に公開しないので http://{jenkins-web-server-host-addr}:{jenkins-port}/ とする。

== メモ

=== Dockerコンテナ内でDockerコンテナを実行できない

上で実行した `jenkins-blueocean` で `docker run` すると、以下のようにエラーが発生してコンテナを実行できない。
これだとJenkinsのジョブでDockerコマンドを実行することができない。
[source, console, options="linenums,nowrap"]
----
jenkins@7f06bfe79c98:/$ docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
2db29710123e: Pull complete
Digest: sha256:7d246653d0511db2a6b2e0436cfd0e52ac8c066000264b3ce63331ac66dca625
Status: Downloaded newer image for hello-world:latest
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: unable to apply cgroup configuration: mkdir /sys/fs/cgroup/cpuset/docker: permission denied: unknown.
ERRO[0007] error waiting for container: context canceled
----
ディレクトリへの書き込み権限がないためにエラーになっているので、DockerデーモンをRootlessモードで実行しているのが原因？

dind(Docker in Docker)はあまり推奨されていないようなので、素直にJenkinsコンテナ内に直接実行環境を構築するのがいいかもしれない。
あるいはJenkinsスレーブのコンテナを作成して、その中に実行環境を構築するとか。

[bibliography]
== 参考文献

* [[[docker-storage-volume, 1]]] https://matsuand.github.io/docs.docker.jp.onthefly/storage/volumes/[ボリュームの利用 | Docker ドキュメント]