[[jenkins-setup]]
= Jenkins環境構築
include::base_attributes.adoc[]
// jenkinsのホストのIPアドレス
:jenkins-web-server-host-addr: localhost
// jenkinsのポート番号
:jenkins-port: 8080

本章では、Docker上にJenkins環境を構築する手順を説明する。

== 環境

xref:docker_setup.adoc#docker-setup[Docker環境構築] に従い環境構築実施済み。

== インストール

https://www.jenkins.io/doc/book/installing/docker/ に従う。

[[create-bridge-network]]
=== ブリッジネットワーク作成

Dockerコンテナ間で通信するにはブリッジネットワークを作成する必要があるので作成する。

[source, console, linenums]
----
$ docker network create jenkins
7ed5933dba63bd8a096d1ecab7d4bdcfb0bd862f4e0fb93bb3c4d39a4a768644
----

=== 試しに実行してみる

Jenkinsを実行する。

[source, bash, options="linenums", subs="attributes+"]
----
docker run \
    --name jenkins \# <1>
    -p 8080:{jenkins-port} \# <2>
    --mount type=volume,source=jenkins-volume,destination=/var/jenkins_home \# <3>
    --network jenkins \# <4>
    jenkins/jenkins:lts-jdk11 # <5>
----
<1> コンテナの名前を指定する。指定しない場合はランダムな名前がつけられる。名前がランダムだと何のためのコンテナなのかわからないので指定する。
<2> 公開するポート番号を指定する。
<3> データを保存するボリュームを指定する。ボリュームはホスト側の `~/.local/share/docker/volumes/ボリューム名/` に作成される。 footnote:[ボリューム名を指定しなかった場合はランダムな文字列（実際はハッシュ値）が名前に使用される。コンテナにマウントされているボリュームは `docker inspect コンテナID` で出力される内容の"Mounts"に記載されている。]
<4> コンテナを<<create-bridge-network>>で作成したネットワークに接続する。
<5> コンテナのベースになるDockerイメージを指定する。使用するイメージは https://hub.docker.com/r/jenkins/jenkins[jenkins/jenkins - Docker Image | Docker Hub] を参照。

上記コマンドを実行すると、以下のようにadminユーザの初期パスワードが記載されたファイルへのパスが表示される。

[source, console, linenums]
----
Jenkins initial setup is required. An admin user has been created and a password generated.
Please use the following password to proceed to installation:

b528f9670cf44323917d05f83af7108d

This may also be found at: /var/jenkins_home/secrets/initialAdminPassword
----

このファイルはコンテナ内のファイルシステムに保存されている。
このファイルを参照するには、実行中のコンテナに接続する。
（実際にはマウントしているボリュームに保存されているので、ホスト側からボリュームの中のファイルを直接参照することもできる）

// "nowrap"で長い行の折り返しを無効にする
[source, bash, options="linenums,nowrap"]
----
# 実行中のコンテナ一覧を出力
$ docker ps
CONTAINER ID   IMAGE                       COMMAND                  CREATED          STATUS          PORTS                                                  NAMES
137f055ee35e   jenkins/jenkins:lts-jdk11   "/usr/bin/tini -- /u…"   17 minutes ago   Up 17 minutes   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 50000/tcp   determined_archimedes

# 上で確認したコンテナ名を指定してシェルを起動
$ docker exec -it determined_archimedes /bin/bash

# ファイルを参照
$ cat /var/jenkins_home/secrets/initialAdminPassword
b528f9670cf44323917d05f83af7108d

# コンテナから切断
$ exit
----

== 初期設定

=== Unlock Jenkins

http://{jenkins-web-server-host-addr}:{jenkins-port}/ にアクセスする。
adminユーザの初期パスワードを入力する。

=== Customize Jenkins

"Install suggested plugins"を選択する。
推奨されるプラグインがインストールされる。

=== Create First Admin User

管理者ユーザを作成する。
ユーザー名、パスワード、フルネーム、メールアドレスをよしなに設定する。

ここでは以下のとおり設定したものとする。

* ユーザー名: admin
* パスワード: jenkins

=== Instance Configuration

JenkinsのURLを指定する。
ここでは外部に公開しないので http://{jenkins-web-server-host-addr}:{jenkins-port}/ とする。

[appendix]
== Jenkinsノード内でDockerコマンドを実行する

Docker内部のコンテナでJenkinsを実行しているとき、JenkinsからDockerコマンドを実行するには、以下のコマンドを実行する。
コマンドの説明は https://www.jenkins.io/doc/book/installing/docker/#on-macos-and-linux をGoogle翻訳により翻訳したものである。

NOTE: どういう操作をしているのかよくわかってない。

[source, bash, linenums]
----
docker run \
  --name jenkins-docker \# <1>
  --rm \# <2>
  --detach \# <3>
  --privileged \# <4>
  --network jenkins \# <5>
  --network-alias docker \# <6>
  --env DOCKER_TLS_CERTDIR=/certs \#<7>
  --volume jenkins-docker-certs:/certs/client \# <8>
  --volume jenkins-data:/var/jenkins_home \# <9>
  --publish 2376:2376 \# <10>
  docker:dind \# <11>
  --storage-driver overlay2 # <12>
----
<1> (オプション) イメージの実行に使用する Docker コンテナー名を指定します。デフォルトでは、Docker はコンテナーの一意の名前を生成します。
<2> (オプション) シャットダウン時に Docker コンテナ (Docker イメージのインスタンス) を自動的に削除します。
<3> (オプション) バックグラウンドで Docker コンテナーを実行します。このインスタンスは、後で `docker stop jenkins-docker` を実行して停止できます。
<4> DockerでDockerを実行するには、現在、正しく機能するために特権アクセスが必要です。この要件は、新しいLinuxカーネルバージョンで緩和される可能性があります。
<5> これは、前の手順で作成したネットワークに対応しています。
<6> Docker コンテナー内の Docker を `jenkins` ネットワーク内のホスト名 `docker` として使用できるようにします。
<7> Docker サーバーでの TLS の使用を有効にします。特権コンテナーを使用するため、これをお勧めしますが、以下で説明する共有ボリュームを使用する必要があります。この環境変数は、Docker TLS 証明書が管理されるルート ディレクトリを制御します。
<8> コンテナ内の `/certs/client` ディレクトリを、上記で作成した `jenkins-docker-certs` という名前のDockerボリュームにマップします。
<9> コンテナ内の `/var/jenkins_home` ディレクトリを `jenkins-data` という名前のDockerボリュームにマップします。これにより、このDockerコンテナのDockerデーモンによって制御される他のDockerコンテナがJenkinsからデータをマウントできるようになります。
<10> （オプション）ホストマシンのDockerデーモンポートを公開します。これは、ホストマシンで `docker` コマンドを実行して、この内部Dockerデーモンを制御する場合に役立ちます。
<11> `docker:dind` イメージ自体。このイメージは、コマンド `docker image pull docker:dind` を使用して、実行する前にダウンロードできます。
<12> Docker ボリュームのストレージドライバー。サポートされているオプションについては、「Dockerストレージドライバー」を参照してください。

[bibliography]
== 参考文献

* [[[docker-storage-volume, 1]]] https://matsuand.github.io/docs.docker.jp.onthefly/storage/volumes/[ボリュームの利用 | Docker ドキュメント]